name: Medievo-Utils
version: ${project.version}
main: com.bgmbox.medievoutils.MedievoUtils
authors: [BGMP, BGMM, BGem]
description: Utilidades complementarias para el plugin medieval
commands:
  gamemode:
    usage: /gamemode
    description: Sets your gamemode.
    aliases: [gm]