name: Medievo-Utils
version: ${project.version}
main: org.elmedievo.medievoutils.MedievoUtils
authors: [BGMP, BGMM, BGem]
description: Utilidades complementarias para el plugin medieval
commands:
  broadcast:
    usage: /broadcast
    description: Broadcasts a message,
    aliases: [br]
  head:
    usage: /head
    description: Gives you any player's head.
    aliases: [skull, ph]
  gamemode:
    usage: /gamemode
    description: Sets your gamemode.
    aliases: [gm]
  teleport:
    usage: /teleport
    description: Teleports you.
    aliases: [tp]
  message:
    usage: /message
    description: Send a private messages to other players.
    aliases: [msg, pm]
  reply:
    usage: /reply
    description: Replies to the last private message sent or received.
    aliases: [r]