name: Medievo-Utils
version: ${project.version}
main: org.elmedievo.MedievoUtils
authors: [BGMP, BGMM, BGem]
description: Utilidades complementarias para el plugin medieval
commands:
  gamemode:
    usage: /gamemode
    description: Sets your gamemode.
    aliases: [gm]
  broadcast:
    usage: /broadcast
    description: Broadcasts a message,
    aliases: [br]
  teleport:
    usage: /teleport
    description: Teleports you.
    aliases: [tp]